#pragma once
#ifndef _IMGUIX_CONFIG_FONTS_HPP_INCLUDED
#define _IMGUIX_CONFIG_FONTS_HPP_INCLUDED

#ifndef IMGUIX_FONTS_DIR
#   define IMGUIX_FONTS_DIR u8"data/resources/fonts"
#endif

#ifndef IMGUIX_FONTS_CONFIG
#   define IMGUIX_FONTS_CONFIG u8"data/resources/fonts/fonts.json"
#endif

#ifndef IMGUIX_MATERIAL_ICONS_BASELINE_18PX
#   define IMGUIX_MATERIAL_ICONS_BASELINE_18PX 5.0f
#endif

#ifndef IMGUIX_MATERIAL_ICONS_BASELINE_16PX
#   define IMGUIX_MATERIAL_ICONS_BASELINE_16PX 4.0f
#endif

#endif // _IMGUIX_CONFIG_FONTS_HPP_INCLUDED
