# cmake/ImGuiXDemos.cmake

function(imguix_add_imgui_demo tgt)
    if(NOT TARGET ${tgt})
        message(FATAL_ERROR "Target ${tgt} not found")
    endif()
    if(NOT DEFINED IMGUI_DIR OR IMGUI_DIR STREQUAL "")
        set(IMGUI_DIR "${PROJECT_SOURCE_DIR}/libs/imgui")
    endif()
    if(EXISTS "${IMGUI_DIR}/imgui_demo.cpp")
        target_sources(${tgt} PRIVATE "${IMGUI_DIR}/imgui_demo.cpp")
    else()
        message(WARNING "imgui_demo.cpp not found at ${IMGUI_DIR}")
    endif()
endfunction()

function(imguix_add_implot_demo tgt)
    if(NOT TARGET ${tgt})
        message(FATAL_ERROR "Target ${tgt} not found")
    endif()
    if(NOT DEFINED IMPLOT_DIR OR IMPLOT_DIR STREQUAL "")
        set(IMPLOT_DIR "${PROJECT_SOURCE_DIR}/libs/implot")
    endif()
    if(EXISTS "${IMPLOT_DIR}/implot_demo.cpp")
        target_sources(${tgt} PRIVATE "${IMPLOT_DIR}/implot_demo.cpp")
    else()
        message(WARNING "implot_demo.cpp not found at ${IMPLOT_DIR}")
    endif()
endfunction()
